#! /usr/bin/env bash

ADHOCSH_COMMAND=git \
ADHOCSH_COMPLETION=/usr/share/bash-completion/completions/git \
ADHOCSH_SUBCOMMANDS=$(
	source $ADHOCSH_COMPLETION
	__git_list_all_commands
) \
bash --rcfile "$(readlink -f "$(dirname "$0")/../adhocrc")"

