#! /usr/bin/env bash

export ADHOCSH_COMMAND=task
export ADHOCSH_COMPLETION=/usr/share/bash-completion/completions/task
export ADHOCSH_SUBCOMMANDS=$(
	task rc.verbose:nothing rc.hooks:off _commands | grep -v '^_';
	task rc.verbose:nothing rc.hooks:off _aliases;
)

bash --rcfile "$(readlink -f "$(dirname "$0")/../adhocrc")"

